# Generated by Django 5.0.14 on 2026-04-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teammembership_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mindmap_collapsed_task_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
