# Generated by Django 5.0.14 on 2026-04-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_mindmap_collapsed_task_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sidebar_color',
            field=models.CharField(
                choices=[
                    ('red', 'Red'),
                    ('orange', 'Orange'),
                    ('green', 'Green'),
                    ('blue', 'Blue'),
                    ('purple', 'Purple'),
                ],
                default='blue',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
