# Generated by Django 5.0.14 on 2026-04-10 08:49

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def set_default_trial_window(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    end_date = timezone.localdate() + timedelta(days=7)
    Profile.objects.filter(trial_ends__isnull=True).update(trial_ends=end_date)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('solo', 'Solo'), ('team', 'Team (up to 5 users)')], default='solo', help_text='Active subscription plan.', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_trial',
            field=models.BooleanField(default=True, help_text='Trial access; manage from admin actions or inline.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trial_ends',
            field=models.DateField(blank=True, help_text='Last day of 7-day trial (inclusive).', null=True),
        ),
        migrations.RunPython(set_default_trial_window, migrations.RunPython.noop),
    ]
