# Generated by Django 5.0.14 on 2026-04-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_plan_alter_profile_is_trial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('solo', 'Solo'), ('team', 'Team (up to 5 users)'), ('team_20', 'Team Pro (up to 20 users)')], default='solo', help_text='Active subscription plan.', max_length=20),
        ),
    ]
