# Generated by Django 5.1.6 on 2026-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ui_mode',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('express', 'Express'), ('pro', 'Pro')], default='pro', help_text='Controls which board views and sidebar links are shown.', max_length=20),
        ),
    ]
