# Generated by Django 5.1.6 on 2026-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_ui_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutorial_seeded',
            field=models.BooleanField(default=False, help_text='True after the welcome tour demo project has been created.'),
        ),
    ]
