# Generated by Django 5.0.14 on 2026-06-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0004_alter_task_options_task_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_type', models.CharField(choices=[('FS', 'Finish → Start'), ('FF', 'Finish → Finish'), ('SS', 'Start → Start'), ('SF', 'Start → Finish')], default='FS', max_length=2)),
                ('lag_days', models.SmallIntegerField(default=0)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_successors', to='planner.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_predecessors', to='planner.task')),
            ],
            options={
                'unique_together': {('predecessor', 'successor', 'dep_type')},
            },
        ),
    ]
